background {
    
    path = ~/.dotfiles/wallpapers/climber1.png
    #path = ~/.dotfiles/wallpapers/cavern.jpg 
    #path = ~/.dotfiles/wallpapers/space-3.jpg
    blur_size = 3 # the size of blur on image
    blur_passes = 2 # how iteration u do on the image
    
    #zindex = 
 
}
