
general {
	hide_cursor = true
	grace = 0
	ignore_empty_input	= true
	fail_timeout = 1500

}


animations {
    enabled = true
 	bezier = gentleFade, 0.3, 0.0, 0.2, 1.0
    animation = fadeIn, 1, 5, gentleFade
}