#!/usr/bin/env bash

iDIR=~/.dotfiles/icons

# Get brightness
get_backlight() {
	# LIGHT=$(printf "%.0f\n" $(brightnessctl i))
	current_brightness=$(brightnessctl i | grep 'Current brightness' | awk '{print $4}' | tr -d '()' )
	echo "$current_brightness"
	
}

# Get icons
get_icon() {
	backlight=$(brightnessctl g)
	current="${backlight}"
	if [[ ("$current" -ge "0") && ("$current" -le "170") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "170") && ("$current" -le "340") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "340") && ("$current" -le "511") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "511") && ("$current" -le "682") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "682") && ("$current" -le "852") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
	echo  $icon

}

# Notify
notify_user() {
	# echo "$(get_icon)"
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi