#!/usr/bin/bash
while ! swww query >/dev/null 2>&1; do
  sleep 0.2
done

swww img ~/.dotfiles/wallpapers/climber2.png --transition-type grow  --transition-duration 1

  
# IN case using pywayl  `pyhton-pywal16` : && wal -i ~/.dotfiles/wallpapers/space-3.jpg