#!/usr/bin/bash

activeWindowJson=$(hyprctl --instance 0 activewindow -j)

activeWindowClass=$(jq '.class' -r <<< "$activeWindowJson")

#this is what the client thinks it is set to
activeWindowClient=$(jq '.fullscreenClient' -r <<< "$activeWindowJson") # client state

#this is what the hyprland window is set to
activeWindowInternal=$(jq -r '.fullscreen' <<< "$activeWindowJson")

if [[ "$activeWindowClass" == "firefox" ]]; then
    if [[ "$activeWindowInternal" == "0" ]]; then
        hyprctl --instance 0 dispatch  fullscreenstate 2 0 
    else
        hyprctl --instance 0 dispatch  fullscreenstate 0 0 
    fi
else
     hyprctl --instance 0 dispatch fullscreen
fi




#
#case "$currentWindowClass" in
#   "firefox")
#        if [[ "$currentHyprState" == "0" ]]; then
#            hyprctl --instance 0 dispatch  fullscreenstate 2 0 
#        else
#            hyprctl --instance 0 dispatch fullscreenstate 0 0  
#        fi
#        ;;
 #   *)
 #       hyprctl --instance 0 dispatch fullscreen
        ;;
#esac
# hyprctl --instance 0 dispatch fullscreenstate 3
