################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= eDP-1, 1920x1080, auto, 1

### temp

################
### MONITORS ###
################
# See https://wiki.hyprland.org/Configuring/Monitors/

# External monitor on the left (when plugged in)
monitor = DP-2, 1920x1080@60, 0x0, 1

# Laptop monitor on the right
monitor = eDP-1, 1920x1080, 1920x0, 1

# Fallback for any other monitor plugged in later
monitor = , preferred, auto, 1

#################
### WORKSPACES ##
#################

# When DP-2 is connected: ws 1 goes there, rest on laptop
# When DP-2 is unplugged: Hyprland auto-moves ws 1 to eDP-1
workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:eDP-1, default:true
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
#workspace = 6, monitor:eDP-1
#workspace = 7, monitor:eDP-1
#workspace = 8, monitor:eDP-1
#workspace = 9, monitor:eDP-1
#workspace = 10, monitor:eDP-1